# Generated by Django 5.1.6 on 2025-04-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='client_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='client_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_method',
            field=models.CharField(choices=[('standard', 'Standard'), ('express', 'Express')], default='standard', max_length=50),
        ),
    ]
